INSERT INTO ECOM.USER_ROLE ("ROLE") VALUES ('CONSUMER');
INSERT INTO ECOM.USER_ROLE ("ROLE") VALUES ('SELLER');
INSERT INTO ECOM.USER_ROLE ("ROLE") VALUES ('ADMIN');

INSERT INTO ECOM.PRODUCT_CATEGORY ("CATEGORY") VALUES ('Fashion');
INSERT INTO ECOM.PRODUCT_CATEGORY ("CATEGORY") VALUES ('Electronics');
INSERT INTO ECOM.PRODUCT_CATEGORY ("CATEGORY") VALUES ('Books');
INSERT INTO ECOM.PRODUCT_CATEGORY ("CATEGORY") VALUES ('Groceries');
INSERT INTO ECOM.PRODUCT_CATEGORY ("CATEGORY") VALUES ('Medicines');

INSERT INTO ECOM.E_USER ("USERNAME","PASSWORD") VALUES('jack','pass_word');
INSERT INTO ECOM.E_USER ("USERNAME","PASSWORD") VALUES('bob','pass_word');
INSERT INTO ECOM.E_USER ("USERNAME","PASSWORD") VALUES('apple','pass_word');
INSERT INTO ECOM.E_USER ("USERNAME","PASSWORD") VALUES('glaxo','pass_word');

INSERT INTO ECOM.CART ("TOTAL_AMOUNT","USER_ID") VALUES (20,1);
INSERT INTO ECOM.CART ("TOTAL_AMOUNT","USER_ID") VALUES (0,2);

INSERT INTO ECOM.E_USER_ROLES("USER_USER_ID","ROLES_ROLE_ID") VALUES (1,1);
INSERT INTO ECOM.E_USER_ROLES("USER_USER_ID","ROLES_ROLE_ID") VALUES (2,1);
INSERT INTO ECOM.E_USER_ROLES("USER_USER_ID","ROLES_ROLE_ID") VALUES (3,2);
INSERT INTO ECOM.E_USER_ROLES("USER_USER_ID","ROLES_ROLE_ID") VALUES (4,3);

INSERT INTO ECOM.PRODUCT ("PRICE","PRODUCT_NAME","CATEGORY_ID","SELLER_ID") VALUES (29190, 'Apple iPad 10.2 8th Gen WiFi iOS Tablet', 2, 3);
INSERT INTO ECOM.PRODUCT ("PRICE","PRODUCT_NAME","CATEGORY_ID","SELLER_ID") VALUES (10, 'Crocin pain relief tablet', 5, 4);
 
INSERT INTO ECOM.CART_PRODUCT ("QUANTITY","CART_ID","PRODUCT_PRODUCT_ID") VALUES(1, 2, 2);
